spring.application.name=checkpoint2
server.port=8080

# Configurações do MySQL
# O parâmetro createDatabaseIfNotExist tenta criar o banco sozinho se ele não existir
spring.datasource.url=jdbc:mysql://localhost:3306/checkpoint_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=fiap
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Desative o H2 (Já que você vai de MySQL agora)
spring.h2.console.enabled=false